includeNewer: true
threshold: 70
toLower: false

indices:

  - name: date
    applyFilter: false
    cardinalityThreshold: 0
    pattern: ""
    toLower: false
    type: basic
    weight: 30

  - name: categories
    applyFilter: false
    cardinalityThreshold: 0
    pattern: ""
    toLower: false
    type: basic
    weight: 60

  - name: tags
    applyFilter: false
    cardinalityThreshold: 0
    pattern: ""
    toLower: false
    type: basic
    weight: 90